---
title: "tidyr包学习笔记"
author: "Fang Yongchao"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_section: true
  runtime: shiny
---

```{r PACKAGES, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
```

# 变量名为变量值

```{r}
# PPT中经常出现此类表格，可读性强，但是难以操作
(pew <- tibble(religion = c("Agnostic", "Atheist", "Hindu"),
               '<$10k' = c(27, 12, 1),
               '$10-20k' = c(34, 27, 9),
               '$20-30k' = c(60, 37, 7)))
```

```{r}
# 第三个参数用于选取前两个参数key和value作用于哪些列
# 可以使用列名也可使用列号，还可以分开一个个选取
pew %>% gather(income, frequency, -religion)
```

# 列中有不同变量的值

```{r}
(tb <- tibble(year = c(2001:2005),
              demo = c("m.04", "f..12", "m.06", "m.10", "f.18"),
              n = sample(5)))
```

```{r}
# 该函数貌似必须有稳定的分隔符，或是在固定位置分割
# 假设demo是male04，female123这样的值就无效了
tb %>% separate(demo, c("sex", "age"), "[.]+")
```

# 变量值为变量名，变量名为变量值

```{r}
(weather <- tibble(
  month = rep(1:6, each = 2),
  element = rep(c("tmax", "tmin"), 6),
  d1 = sample(12),
  d2 = sample(12),
  d3 = sample(12)
  ))
```

```{r}
# gather()和spread()一起使用
# spread一般不需要加太多参数
weather %>% 
  gather(day, value, d1:d3) %>% 
  spread(element, value)
```

# 一表中有多个不同变量

- 考虑把这些变量做成单独一张表然后非重复项形成一个主键，把主键放在原表中就行了。

# 不同表中有相同变量

```{r, eval=FALSE}
# NOT RUN
library(purrr)
paths <- dir("data", pattern = "\\.csv$", full.names = TRUE)
names(paths) <- basename(paths)
map_dfr(paths, read.csv, stringAsFactors = FALSE, .id = "filename")
```

