legend.text.align: element_align
legend.title.align: element_align

legend.box: element_direction
legend.direction: element_direction

legend.box.just: element_just

legend.justification: element_justification

line: element_line
axis.ticks: element_line
axis.ticks.x: element_line
axis.ticks.x.top: element_line
axis.ticks.x.bottom: element_line
axis.ticks.y: element_line
axis.ticks.y.left: element_line
axis.ticks.y.right: element_line
axis.line: element_line
axis.line.x: element_line
axis.line.x.top: element_line
axis.line.x.bottom: element_line
axis.line.y: element_line
axis.line.y.left: element_line
axis.line.y.right: element_line
panel.grid: element_line
panel.grid.major: element_line
panel.grid.major.x: element_line
panel.grid.major.y: element_line
panel.grid.minor: element_line
panel.grid.minor.x: element_line
panel.grid.minor.y: element_line

panel.ontop: element_logical

legend.box.margin: element_margin
legend.margin: element_margin
plot.margin: element_margin

strip.placement: element_placement

legend.position: element_position

rect: element_rect
legend.key: element_rect
legend.box.background: element_rect
legend.background: element_rect
panel.background: element_rect
panel.border: element_rect
plot.background: element_rect
strip.background: element_rect
strip.background.x: element_rect
strip.background.y: element_rect

plot.tag.position: element_tag_position

text: element_text
title: element_text
axis.title: element_text
axis.title.x: element_text
axis.title.x.top: element_text
axis.title.x.bottom: element_text
axis.title.y: element_text
axis.title.y.left: element_text
axis.title.y.right: element_text
axis.text: element_text
axis.text.x: element_text
axis.text.x.top: element_text
axis.text.x.bottom: element_text
axis.text.y: element_text
axis.text.y.left: element_text
axis.text.y.right: element_text
legend.text: element_text
legend.title: element_text
plot.title: element_text
plot.subtitle: element_text
plot.caption: element_text
plot.tag: element_text
strip.text: element_text
strip.text.x: element_text
strip.text.y: element_text
strip.text.y.left: element_text

plot.title.position: element_title_position
plot.caption.position: element_title_position

axis.ticks.length: element_unit
axis.ticks.length.x: element_unit
axis.ticks.length.x.top: element_unit
axis.ticks.length.x.bottom: element_unit
axis.ticks.length.y: element_unit
axis.ticks.length.y.left: element_unit
axis.ticks.length.y.right: element_unit

legend.spacing: element_unit
legend.spacing.x: element_unit
legend.spacing.y: element_unit
legend.key.size: element_unit
legend.key.height: element_unit
legend.key.width: element_unit
legend.box.spacing: element_unit
panel.spacing: element_unit
panel.spacing.x: element_unit
panel.spacing.y: element_unit
strip.switch.pad.grid: element_unit
strip.switch.pad.wrap: element_unit


# other
aspect.ratio: element_number



