library(shiny)
library(ggplot2)
library(yaml)
library(colourpicker)
library(shinyWidgets)
library(stringr)
library(shinyjs)
library(shinycssloaders)
library(dplyr)
library(shinyAce)

source("utils/elements.R")
source("init.R")
source("utils/helpers.R")

source("modules/default_setting.R")
source("modules/own_setting.R")
source("modules/header.R")
source("modules/element_align.R")
source("modules/element_direction.R")
source("modules/element_just.R")
source("modules/element_justification.R")
source("modules/element_line.R")
source("modules/element_logical.R")
source("modules/element_margin.R")
source("modules/element_placement.R")
source("modules/element_position.R")
source("modules/element_rect.R")
source("modules/element_tag_position.R")
source("modules/element_text.R")
source("modules/element_title_position.R")
source("modules/element_unit.R")

# source("modules/element_number.R")
